In [1]:
!pip install folium

Collecting folium
  Downloading folium-0.12.1-py2.py3-none-any.whl (94 kB)
Collecting branca>=0.3.0
  Downloading branca-0.4.2-py3-none-any.whl (24 kB)
Requirement already satisfied: numpy in c:\users\admin\anaconda3\lib\site-packages (from folium) (1.20.1)
Requirement already satisfied: requests in c:\users\admin\anaconda3\lib\site-packages (from folium) (2.25.1)
Requirement already satisfied: jinja2>=2.9 in c:\users\admin\anaconda3\lib\site-packages (from folium) (2.11.3)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\admin\anaconda3\lib\site-packages (from jinja2>=2.9->folium) (1.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\anaconda3\lib\site-packages (from requests->folium) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests->folium) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests->folium) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\admin\anaconda3\lib\site-packages (from requests->folium) (4.0.0)
Installing collected packages: branca, folium
Successfully installed branca-0.4.2 folium-0.12.1

In [7]:
import pandas as pd
df = pd.read_csv('csv/부산광역시_부산진구_가로수현황_20201123.csv',encoding="euc-kr")
df

,위치명,위도,경도,구간시점,구간종점,식재거리,총합계,왕벚나무,은행나무,느티나무,...,메타세콰이아,칠엽수,튤립나무,벽오동,후박나무,먼나무,가시나무,녹나무,구군명,데이터기준일자
0,부산광역시 부산진구 서면문화로,35.1605598,129.056036,새싹로 59,가야대로 785,600,97,0,78,0,...,0,0,0,0,0,0,0,0,부산진구,2020-11-23
1,부산광역시 부산진구 동성로,35.1590126,129.065801,동성로 151,부산동성고등학교,600,48,0,41,0,...,0,0,0,0,0,0,0,0,부산진구,2020-11-23
2,부산광역시 부산진구 시민공원로,35.1646794,129.056883,시민공원로 8,동평로 경계,740,543,0,0,505,...,0,0,0,0,38,0,0,0,부산진구,2020-11-23
3,부산광역시 부산진구 부전로,35.1579655,129.057953,부전로 87,범전로13,3510,128,0,0,0,...,0,0,0,117,0,11,0,0,부산진구,2020-11-23
4,부산광역시 부산진구 범전로,35.1647429,129.062218,범전로13,범전로 807,660,25,0,0,25,...,0,0,0,0,0,0,0,0,부산진구,2020-11-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,부산광역시 부산진구 개금온정로,35.1544606,129.025160,개금온정로17번길 77,가야대로 489,390,32,5,27,0,...,0,0,0,0,0,0,0,0,부산진구,2020-11-23
60,부산광역시 부산진구 백양관문로 지선,35.1674447,129.026977,부산국제고등학교,동일스위트아파트,253,52,45,0,7,...,0,0,0,0,0,0,0,0,부산진구,2020-11-23
61,부산광역시 부산진구 화지로,35.1760575,129.064476,부산정보고등학교,동평로 353,288,20,0,0,20,...,0,0,0,0,0,0,0,0,부산진구,2020-11-23
62,부산광역시 부산진구 만리산로,35.1460165,129.052772,범천동 DS협성엘리시안,범천동 DS협성엘리시안,112,14,14,0,0,...,0,0,0,0,0,0,0,0,부산진구,2020-11-23
63,부산광역시,35.1510299,129.044208,엄광로,지선,192,23,0,0,23,...,0,0,0,0,0,0,0,0,부산진구,2020-11-23

In [27]:
import csv
import folium

file = open('csv/부산광역시_부산진구_가로수현황_20201123.csv','r',encoding="euc-kr")
rdr = csv.reader(file)

next(rdr,None) #메타데이터 스킵

#읽은 내용 보기
#위치명[0], 위도[1], 경도[2]
for idx,tmp in enumerate(rdr):
    if idx == 0: #최초 1번 객체 만들기, 시작위치의 중심이 location에 정의된 곳
        map_data = folium.Map(location=[float(tmp[1]),float(tmp[2])], zoom_size=12, zoom_start=13)
    
    folium.Marker([float(tmp[1]),float(tmp[2])],popup=tmp[0]).add_to(map_data)
    print(idx,tmp[0][11:],tmp[1],tmp[2])
    
map_data.save('map/ex01.html')

0 서면문화로 35.1605598 129.0560362
1 동성로 35.1590126 129.0658008
2 시민공원로 35.1646794 129.0568825
3 부전로 35.1579655 129.0579533
4 범전로 35.1647429 129.0622177
5 중앙대로 783번길 35.1627484 129.0617808
6 백양대로 300번길 35.1561326 129.0186517
7 거제대로 35.1721255 129.0677072
8 연수로 35.1742021 129.0747654
9 진연로 35.1787628 129.0731784
10 서면로 35.1531931 129.0576515
11 월드컵대로 35.1829535 129.0504627
12 가야공원로 35.1486117 129.0291586
13 신천대로 126번길 35.1550124 129.0524807
14 신천대로 165번길 35.1560728 129.050297
15 동천로 35.155889 129.0626192
16 새싹로 35.1704014 129.0512854
17 시민공원로 19번길 35.1653186 129.0516634
18 백양대로 35.1601597 129.036515
19 자유평화로 35.1416903 129.0620084
20 가야벽산아파트길 35.1468628 129.0279363
21 냉정로 35.1507159 129.024434
22 대학로 45번길 35.1515633 129.0364293
23 백양관문로 35.1652868 129.0284986
24 가야대로 548번길 35.1501324 129.0325505
25 가야대로 552번길 35.1502592 129.0335035
26 범일로 35.1437325 129.0593375
27 백양대로 208번길+지선 35.1615535 129.0255372
28 백양관문로 77번길 35.1635604 129.0263548
29 백양산로 55번길+지선일부 35.1738204 129.0307924
30 백양산로 35.1738183 129.0316594
31 당감로 35.1668429 129.0382797
32 황령대로 35.1486807 129.0627465
33 서전로 35.1578332 129.0637334
34 전포대로 199번길 35.1544914 129.0635805
35 당감서로 35.1662542 129.0352231
36 백양순환로 35.1681223 129.0375094
37 백양순환로 35번길 35.1667992 129.0319106
38 백양대로 136번길 35.1631554 129.0336767
39 전포대로 35.1555541 129.0659438
40 신암로 35.1498082 129.051802
41 신천대로 35.1584115 129.0521134
42 성지로 35.1781132 129.0521508
43 복지로 35.1475761 129.0198636
44 가야대로 443번길 35.1544133 129.0210367
45 엄광로 35.1510299 129.0442084
46 동평로 35.1689518 129.0490195
47 중앙대로 35.1587335 129.063596
48 가야대로 35.1545019 129.0334678
49 성지곡로 35.1859841 129.048271
50 진남로 35.16555 129.0731479
51 동평로 183번길 35.1697096 129.0489306
52 초읍천로 35.1787318 129.046807
53 초연로 35.1736047 129.0467586
54 중앙대로 644번길 35.1492282 129.0617453
55 황령대로 30번길 35.1460039 129.0625997
56 자유평화로 37번길 35.14272443 129.0626879
57 시민공원로 20번길 35.1630545 129.0523593
58 범천로 35.1492168 129.0559186
59 개금온정로 35.1544606 129.0251597
60 백양관문로 지선 35.1674447 129.0269767
61 화지로 35.1760575 129.0644758
62 만리산로 35.1460165 129.0527717
63  35.1510299 129.0442084

In [33]:
import csv
import requests
import pandas as pd 

csv_url="http://ihongss.com/resources/train.csv"

with requests.Session() as s:
    download = s.get(csv_url)
    decode_content = download.content.decode('utf-8')
    file = csv.reader(decode_content.splitlines(), delimiter=",")
    
    data = list(file)
    df = pd.DataFrame(data[1:],columns=data[0])
df

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
4,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13,,S
887,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,,1,2,W./C. 6607,23.45,,S
889,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.75,,Q